#!/usr/bin/env python3
"""
Build Script - Package JRT Tech ANALIST Pro 3.4 into a standalone Windows .exe
Uses PyInstaller to create a distributable Windows application.

IMPORTANT: This script MUST be run on a Windows machine.
PyInstaller cannot cross-compile between macOS and Windows.

Usage (on Windows):
  python build_windows.py
"""

import os
import sys
import subprocess
import shutil

# Monkey patch dis._get_const_info to prevent PyInstaller crash on compiler-generated bytecode anomalies
try:
    import dis
    original_get_const_info = dis._get_const_info
    def new_get_const_info(*args, **kwargs):
        try:
            return original_get_const_info(*args, **kwargs)
        except IndexError:
            const_index = args[0] if args else 0
            return (f"<invalid_const_{const_index}>", repr(f"<invalid_const_{const_index}>"))
    dis._get_const_info = new_get_const_info
except Exception as e:
    print(f"[Build] Warning: failed to patch dis module: {e}")

APP_NAME = "JRT Tech ANALIST Pro"
VERSION = "3.4"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MAIN_SCRIPT = os.path.join(SCRIPT_DIR, "AnalistProStudioApp.py")
SERVER_SCRIPT = os.path.join(SCRIPT_DIR, "localhost_server.py")
WEB_DIR = os.path.join(SCRIPT_DIR, "HondaECUTool", "data", "web")
DIST_DIR = os.path.join(SCRIPT_DIR, "dist")
BUILD_DIR = os.path.join(SCRIPT_DIR, "build")

# Icon files (try multiple locations)
ICON_CANDIDATES = [
    os.path.join(SCRIPT_DIR, "icon.ico"),
    os.path.join(SCRIPT_DIR, "HondaECUTool", "data", "web", "favicon.ico"),
]


def check_dependencies():
    """Ensure PyInstaller and other deps are available"""
    deps = {
        "PyInstaller": "pyinstaller",
        "webview": "pywebview",
        "aiohttp": "aiohttp",
        "serial": "pyserial",
    }
    missing = []
    for module_name, pip_name in deps.items():
        try:
            __import__(module_name)
            print(f"  [OK] {pip_name}")
        except ImportError:
            missing.append(pip_name)
            print(f"  [MISSING] {pip_name}")

    if missing:
        print(f"\n[INSTALL] Installing missing dependencies: {', '.join(missing)}")
        subprocess.check_call([sys.executable, "-m", "pip", "install"] + missing)
        print("[INSTALL] Done.\n")


def find_icon():
    """Find the first available icon file."""
    for path in ICON_CANDIDATES:
        if os.path.isfile(path):
            return path
    return None


def collect_data_entries():
    """Build the list of --add-data entries for PyInstaller."""
    sep = ";" if sys.platform == "win32" else ":"
    entries = []

    # 1. Web assets (HTML/CSS/JS/images)
    if os.path.isdir(WEB_DIR):
        entries.append(f"{WEB_DIR}{sep}HondaECUTool/data/web")

    # 2. Server script & seed_key_provider
    if os.path.isfile(SERVER_SCRIPT):
        entries.append(f"{SERVER_SCRIPT}{sep}.")
    seed_key = os.path.join(SCRIPT_DIR, "seed_key_provider.py")
    if os.path.isfile(seed_key):
        entries.append(f"{seed_key}{sep}.")

    # 3. Drivers package (HondaECU, HondaECU_Serial, etc.)
    drivers_dir = os.path.join(SCRIPT_DIR, "drivers")
    if os.path.isdir(drivers_dir):
        entries.append(f"{drivers_dir}{sep}drivers")

    # 4. Protocols package
    protocols_dir = os.path.join(SCRIPT_DIR, "protocols")
    if os.path.isdir(protocols_dir):
        entries.append(f"{protocols_dir}{sep}protocols")

    # 5. Framework package (core, flash, transport, plugins, live_data, database, analyzer, developer)
    framework_dir = os.path.join(SCRIPT_DIR, "framework")
    if os.path.isdir(framework_dir):
        entries.append(f"{framework_dir}{sep}framework")

    # 6. Plugin JSON configs
    plugins_dir = os.path.join(SCRIPT_DIR, "plugins")
    if os.path.isdir(plugins_dir):
        entries.append(f"{plugins_dir}{sep}plugins")

    # 7. Logs directory (create empty one so path exists)
    logs_dir = os.path.join(SCRIPT_DIR, "logs")
    os.makedirs(logs_dir, exist_ok=True)
    # Create a placeholder so PyInstaller includes the directory
    placeholder = os.path.join(logs_dir, ".gitkeep")
    if not os.path.exists(placeholder):
        with open(placeholder, "w") as f:
            f.write("")
    entries.append(f"{logs_dir}{sep}logs")

    return entries


def collect_hidden_imports():
    """Return list of hidden imports needed for the frozen app."""
    return [
        # pywebview & Windows GUI rendering backends
        "webview",
        "webview.platforms",
        "webview.platforms.winforms",
        "webview.platforms.mshtml",
        "webview.platforms.edgehtml",
        "webview.platforms.edgechromium",
        "webview.platforms.cef",
        "webview.js",
        "webview.js.api",
        "clr",
        "clr_loader",
        "pythonnet",
        "win32gui",
        "win32con",
        "win32api",
        "bottle",
        "ctypes.wintypes",



        # aiohttp server
        "aiohttp",
        "aiohttp.web",
        "aiohttp.web_runner",
        "aiohttp.web_server",
        "aiohttp.web_app",
        "aiohttp.web_request",
        "aiohttp.web_response",
        "aiohttp.web_routedef",
        "aiohttp.web_middlewares",
        "aiohttp.web_exceptions",
        "aiohttp.web_fileresponse",
        "aiohttp.web_urldispatcher",
        "aiohttp.web_ws",
        # multidict (aiohttp dependency)
        "multidict",
        "multidict._multidict",
        # yarl (aiohttp dependency)
        "yarl",
        "yarl._quoting",
        # frozenlist (aiohttp dependency)
        "frozenlist",
        # serial / pyserial
        "serial",
        "serial.tools",
        "serial.tools.list_ports",
        "serial.tools.list_ports_common",
        "serial.tools.list_ports_windows",
        "serial.serialutil",
        "serial.serialwin32",
        # drivers
        "drivers",
        "drivers.HondaECU",
        "drivers.HondaECU_Serial",
        "drivers.HondaPGMFI",
        "drivers.CustomFTDI",
        "drivers.KawasakiKDS",
        "drivers.SuzukiSDS",
        "drivers.YamahaYEC",
        "drivers.ecmids",
        "drivers.ecu_driver_base",
        "drivers.hardware_adapter",
        "drivers.plugin_engine",
        # protocols
        "protocols",
        "protocols.session",
        "protocols.transport",
        "protocols.security",
        "protocols.state_machine",
        "protocols.models",
        "protocols.constants",
        "protocols.exceptions",
        # framework
        "framework",
        "framework.core",
        "framework.core.models",
        "framework.core.exceptions",
        "framework.core.constants",
        "framework.core.state_machine",
        "framework.flash",
        "framework.flash.base_flash",
        "framework.flash.keihin_flash",
        "framework.flash.recovery",
        "framework.transport",
        "framework.transport.base",
        "framework.transport.factory",
        "framework.transport.serial_transport",
        "framework.transport.simulated_transport",
        "framework.plugins",
        "framework.plugins.factory",
        "framework.plugins.base_protocol",
        "framework.plugins.keihin_kline",
        "framework.live_data",
        "framework.live_data.repository",
        "framework.live_data.engine",
        "framework.live_data.graph_backend",
        "framework.database",
        "framework.database.ecu_database",
        "framework.analyzer",
        "framework.analyzer.packet_decoder",
        "framework.analyzer.protocol_analyzer",
        "framework.analyzer.session_logger",
        "framework.developer",
        "framework.developer.dev_panel",
        # stdlib that PyInstaller may miss
        "hashlib",
        "zlib",
        "struct",
        "asyncio",
        "concurrent",
        "concurrent.futures",
        "json",
        "tempfile",
        "importlib",
        "importlib.util",
    ]



def build():
    check_dependencies()

    print(f"\n{'='*60}")
    print(f"  Building {APP_NAME} v{VERSION}")
    print(f"  Platform: {'Windows' if sys.platform == 'win32' else sys.platform}")
    print(f"  Python: {sys.version}")
    print(f"{'='*60}\n")

    # Clean previous builds
    for d in [DIST_DIR, BUILD_DIR]:
        if os.path.exists(d):
            try:
                shutil.rmtree(d, ignore_errors=True)
                print(f"[CLEAN] Removed {d}")
            except Exception as e:
                print(f"[CLEAN] Warning clearing {d}: {e}")

    # Collect data and imports
    data_entries = collect_data_entries()
    hidden_imports = collect_hidden_imports()
    icon_file = find_icon()

    # Safe excludes to shrink bundle size without breaking pywebview/asyncio/aiohttp dependencies
    excludes = [
        "numpy", "PIL", "Pillow", "jinja2", "markupsafe",
        "tkinter", "_tkinter", "tcl", "tk", "matplotlib", "scipy", "pandas",
        "IPython", "notebook", "jupyter", "wx", "PyQt5", "PyQt6", "PySide2",
        "PySide6", "scapy", "unittest", "pydoc", "doctest"
    ]




    # Build PyInstaller command
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name", APP_NAME,
        "--windowed",                    # No console window
        "--onedir",                      # Single directory output
        "--noconfirm",                   # Overwrite without asking
        "--clean",                       # Clean cache
    ]

    for exc in excludes:
        cmd.extend(["--exclude-module", exc])


    # Add all data entries
    for entry in data_entries:
        cmd.extend(["--add-data", entry])

    # Add all hidden imports
    for imp in hidden_imports:
        cmd.extend(["--hidden-import", imp])

    # Add icon if found
    if icon_file:
        cmd.extend(["--icon", icon_file])
        print(f"[ICON] Using icon: {icon_file}")
    else:
        print("[ICON] No icon file found, building without icon")

    # Add main script
    cmd.append(MAIN_SCRIPT)

    print(f"[BUILD] Data entries: {len(data_entries)}")
    print(f"[BUILD] Hidden imports: {len(hidden_imports)}")
    print("[BUILD] Running PyInstaller...\n")

    try:
        from PyInstaller import __main__ as pyi_main
        pyi_args = cmd[3:]  # Skip 'python -m PyInstaller'
        pyi_main.run(pyi_args)
    except SystemExit as e:
        if e.code != 0:
            print(f"\n[BUILD] PyInstaller exited with code {e.code}")
            return False
    except Exception as e:
        print(f"\n[BUILD] PyInstaller error: {e}")
        return False

    # Verify output
    exe_dir = os.path.join(DIST_DIR, APP_NAME)
    exe_file = os.path.join(exe_dir, f"{APP_NAME}.exe")

    if os.path.exists(exe_file):
        size_mb = os.path.getsize(exe_file) / (1024 * 1024)
        total_size = sum(
            os.path.getsize(os.path.join(dp, f))
            for dp, dn, filenames in os.walk(exe_dir)
            for f in filenames
        ) / (1024 * 1024)

        print(f"\n{'='*60}")
        print(f"  [SUCCESS] BUILD SUCCESSFUL!")

        print(f"  EXE: {exe_file}")
        print(f"  EXE Size: {size_mb:.1f} MB")
        print(f"  Total Folder: {total_size:.1f} MB")
        print(f"{'='*60}")
        print(f"\n  To run: double-click \"{APP_NAME}.exe\" in dist\\{APP_NAME}\\")
        print(f"  To distribute: zip the entire dist\\{APP_NAME}\\ folder")
        return True
    else:
        print(f"\n[BUILD] EXE not found at: {exe_file}")
        return False


def create_installer_nsis():
    """Generate NSIS installer script (optional, requires NSIS installed on Windows)"""
    nsis_script = f"""; JRT Tech ANALIST Pro - NSIS Installer Script
; Requires: NSIS (https://nsis.sourceforge.io/)
; Build:    makensis installer.nsi

!include "MUI2.nsh"

Name "{APP_NAME} v{VERSION}"
OutFile "dist\\{APP_NAME} Setup {VERSION}.exe"
InstallDir "$PROGRAMFILES\\{APP_NAME}"
RequestExecutionLevel admin

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_LANGUAGE "English"

Section "Install"
    SetOutPath "$INSTDIR"
    File /r "dist\\{APP_NAME}\\*.*"

    CreateDirectory "$SMPROGRAMS\\{APP_NAME}"
    CreateShortCut "$SMPROGRAMS\\{APP_NAME}\\{APP_NAME}.lnk" "$INSTDIR\\{APP_NAME}.exe"
    CreateShortCut "$DESKTOP\\{APP_NAME}.lnk" "$INSTDIR\\{APP_NAME}.exe"

    WriteUninstaller "$INSTDIR\\Uninstall.exe"

    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{APP_NAME}" "DisplayName" "{APP_NAME}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{APP_NAME}" "UninstallString" "$INSTDIR\\Uninstall.exe"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{APP_NAME}" "DisplayVersion" "{VERSION}"
SectionEnd

Section "Uninstall"
    RMDir /r "$INSTDIR"
    RMDir /r "$SMPROGRAMS\\{APP_NAME}"
    Delete "$DESKTOP\\{APP_NAME}.lnk"
    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{APP_NAME}"
SectionEnd
"""
    nsis_path = os.path.join(SCRIPT_DIR, "installer.nsi")
    with open(nsis_path, "w") as f:
        f.write(nsis_script)
    print(f"\n[NSIS] Installer script written to: {nsis_path}")
    print(f"[NSIS] To create Windows Setup installer: makensis installer.nsi")


if __name__ == "__main__":
    success = build()
    if success:
        create_installer_nsis()
        print("\n[DONE] Windows build complete!")
    else:
        print("\n[FAIL] Build failed.")
        sys.exit(1)
